//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasculaInventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenesDeTrabajo
    {
        public int idOdT { get; set; }
        public string folioOdT { get; set; }
        public string ordenDeTrabajo { get; set; }
        public int idMaquina { get; set; }
        public int kilosOdT { get; set; }
        public System.DateTime fechaOdT { get; set; }
        public int idProducto { get; set; }
    }
}
