//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasculaInventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.ordenesDeTrabajo = new HashSet<ordenesDeTrabajo>();
            this.registroDePeso = new HashSet<registroDePeso>();
        }
    
        public int idProducto { get; set; }
        public string descProducto { get; set; }
        public int idAditivo { get; set; }
        public int idColor { get; set; }
        public string medida { get; set; }
        public string calibre { get; set; }
        public Nullable<int> KGxRollo { get; set; }
        public Nullable<int> metros { get; set; }
        public string soplo { get; set; }
        public string bajaDencidad { get; set; }
        public string linealButen { get; set; }
        public string antiblock { get; set; }
        public bool tub { get; set; }
        public bool ax1l { get; set; }
        public bool ax2l { get; set; }
        public bool pp { get; set; }
        public bool ppRefil { get; set; }
    
        public virtual aditivos aditivos { get; set; }
        public virtual colores colores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenesDeTrabajo> ordenesDeTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registroDePeso> registroDePeso { get; set; }
    }
}
