//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasculaInventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class registroDePeso
    {
        public int idRdP { get; set; }
        public int idOdT { get; set; }
        public int idProducto { get; set; }
        public double peso { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    }
}
