//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasculaInventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculos
    {
        public int idVehiculo { get; set; }
        public string descVehiculo { get; set; }
        public string placasVehiculo { get; set; }
    }
}
